<?php

date_default_timezone_set('Europe/Belgrade');

return array(
    'baseUrl' => 'https://solid.djavolak.info',
    'siteName' => 'Solidarity tools',
    'appName' => 'solidarity',
    'appType' => '',
    'redirectUri' => '/donor/view/',
    'timezone' => 'Europe/Belgrade',
    'adminPath' => '',
    'imageBasePath' => IMAGES_PATH,
    'ignoreTrailingSlash' => true,
    'compileAssets' => false,
    'mailer' => [
        'from' => 'djavolak@mail.ru',
        'fromName' => 'Mreža Solidarnosti',
        'recipients' => [
            'errorNotice' => [
                'djavolak@mail.ru',
            ],
            'general' => [
                'djavolak@mail.ru',
            ],
        ],
        'server' => [],
    ],
    'captcha' => [
        'siteKey' => '',
    ],
    'cliMap' =>  [
        'test' => \Solidarity\Backend\Action\Index::class,
        'donor' => \Solidarity\Backend\Controller\DonorController::class,
        'delegate' => \Solidarity\Backend\Controller\DelegateController::class,
        'educator' => \Solidarity\Backend\Controller\EducatorController::class,
        'educatorImport' => \Solidarity\Backend\Controller\EducatorImportController::class,
        'transactionImport' => \Solidarity\Backend\Controller\TransactionImportController::class,
        'transaction' => \Solidarity\Backend\Controller\TransactionController::class
    ],
    'schoolTypes' => array(
	    'Osnovna škola',
	    'Srednja stručna škola',
	    'Gimnazija',
    ),
	'schoolsMap' => array(
		'Ada'                        => array(
			'Osnovna škola Novak Radonić Mol',
			'Osnovna škola Čeh Karolj',
			'Tehnička škola',
			'Škola za muzičko obrazovanje i vaspitanje Barok Bela',
		),
		'Aleksandrovac'              => array(
			'Osnovna škola Aca Aleksić',
			'Osnovna škola Ivo Lola Ribar',
			'Srednja škola Sveti Trifun',
		),
		'Aleksinac'                  => array(
			'Muzička škola Vladimir Đorđević',
			'Osnovna škola Aca Sinadinovič Loćika',
			'Osnovna škola Vožd Karađorđe',
			'Osnovna škola Vuk Karadžić Žitkovac',
			'Osnovna škola Desanka Maksimović Katun',
			'Osnovna škola Jovan Jovanović Zmaj Aleksinački Rudnik',
			'Osnovna škola Ljupče Nikolić',
			'Osnovna škola Sveti Sava Subotinac',
			'Osnovna škola Stojan Živković Stole Trnjane',
			'Osnovna škola Smeh i suza',
			'Aleksinačka gimnazija',
			'Poljoprivredna škola Šumatovac',
			'Tehnička škola Prota Stevan Dimitrijević',
		),
		'Alibunar'                   => array(
			'Osnovna škola 1. maj Vladimirovac',
			'Osnovna škola 2. oktobar Nikolinci',
			'Osnovna škola 3. oktobar Lokve',
			'Osnovna škola Bratstvo jedinstvo',
			'Osnovna škola Dušan Jerković Banatski Karlovac',
			'Osnovna škola Miloš Crnjanski Ilandža',
			'Osnovna škola Sava Veljković Dobrica',
			'Osnovna škola Tomaš Garig Masarik Janošik',
			'Ekonomsko-trgovinska škola',
		),
		'Apatin'                     => array(
			'Muzička škola Stevan Hristić',
			'Osnovna škola Žarko Zrenjanin',
			'Osnovna škola Ivan Goran Kovačić Sonta',
			'Osnovna škola Jozef Atila Kupusina',
			'Osnovna škola Kiš Ferenc Svilojevo',
			'Osnovna škola Mladost Prigrevica',
			'Gimnazija i stručna škola',
			'Tehnička škola',
		),
		'Aranđelovac'                => array(
			'Osnovna muzička škola Petar Ilić',
			'Osnovna škola Velja Gerasimović Venčane',
			'Osnovna škola Vuk Karadžić Stojnik',
			'Osnovna škola Dušan Radonjić Banja',
			'Osnovna škola Ilija Garašanin',
			'Osnovna škola Ljubomir Ljuba Nenadović Ranilović',
			'Osnovna škola Milan Ilić Čiča',
			'Osnovna škola Miloš Obrenović',
			'Osnovna škola Prvi srpski ustanak Orašac',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Slavko Popović Darosava',
			'Osnovna škola Svetolik Ranković',
			'Gimnazija Miloš Savković',
			'Ekonomsko-ugostiteljska škola Slobodan Minić',
			'Tehnička škola Mileta Nikolić',
		),
		'Arilje'                     => array(
			'Osnovna škola Stevan Čolović',
			'Osnovna škola Brekovo Brekovo',
			'Osnovna škola Jezdimir Tripković Latvica',
			'Osnovna škola Ratko Jovanović Kruščica',
			'Srednja škola Sveti Ahilije',
		),
		'Babušnica'                  => array(
			'Osnovna škola Bratstvo Zvonce',
			'Osnovna škola Despot Stefan Lazarević',
			'Osnovna škola Mladost Veliko Bonjince',
			'Osnovna škola Svetozar Marković Ljuberađa',
			'Osnovna škola Dobrinka Bogdanović Strelac',
			'Srednja škola',
		),
		'Bajina Bašta'               => array(
			'Osnovna škola Dušan Jerković Kostojevići',
			'Osnovna škola Rajak Pavićević',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Stevan Joksimović Rogačica',
			'Gimnazija Josif Pančić',
			'Tehnička škola',
		),
		'Barajevo'                   => array(
			'Srednja škola',
		),
		'Batočina'                   => array(
			'Osnovna škola Sveti Sava',
			'Srednja škola Nikola Tesla',
		),
		'Bač'                        => array(
			'Osnovna škola Aleksa Šantić Vajska',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Ivo Lola Ribar Plavna',
			'Osnovna škola Jan Kolar Selenča',
			'Osnovna škola Moša Pijade Bačko Novo Selo',
			'Poljoprivredna škola',
		),
		'Bačka Palanka'              => array(
			'Muzička škola Stevan Hristić',
			'Osnovna škola 15. oktobar Pivnice',
			'Osnovna škola Aleksa Šantić Gajdobra',
			'Osnovna škola Braća Novakov Silbaš',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Žarko Zrenjanin Obrovac',
			'Osnovna škola Zdravko Čelar Čelarevo',
			'Osnovna škola Mileta Protić Tovariševo',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Heroj Pinki',
			'Osnovna škola Branko Ćopić Mladenovo',
			'Gimnazija 20. oktobar',
			'Srednja stručna škola Radivoj Uvalić',
			'Tehnička škola 9. Maj',
		),
		'Bačka Topola'               => array(
			'Osnovna škola 18.oktobar Novo Orahovo',
			'Osnovna škola Bratstvo jedinstvo Bajša',
			'Osnovna škola Vuk Karadžić Krivaja',
			'Osnovna škola Doža Đerđ Gunaroš',
			'Osnovna škola Nikola Tesla',
			'Osnovna škola Čaki Lajoš',
			'Osnovna Škola Moša Pijade Pačir',
			'Osnovna škola Stari kovač Đula Stara Moravica',
			'Gimnazija i ekonomska škola Dositej Obradović',
			'Poljoprivredna škola',
			'Srednja tehnička škola Šinković Jožef',
			'Škola za osnovno muzičko obrazovanje',
		),
		'Bački Petrovac'             => array(
			'Osnovna Škola Žarko Zrenjanin Maglić',
			'Osnovna škola Jan Amos Komenski Kulpin',
			'Osnovna škola Jan Čajak',
			'Osnovna škola Jožef Marčok Dragutin Gložan',
			'Gimnazija Jan Kolar',
		),
		'Bela Palanka'               => array(
			'Osnovna škola Jovan Aranđelović Crvena Reka',
			'Osnovna škola Ljupče Španac',
			'Srednja škola Niketa Remezijanski',
		),
		'Bela Crkva'                 => array(
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Đorđe Maletić Jasenovo',
			'Osnovna škola Žarko Zrenjanin',
			'Osnovna škola Mara Janković Kusić',
			'Osnovna škola Marko Stojanović Vračev Gaj',
			'Osnovna škola Mihail Sadoveanu Grebenac',
			'Osnovna škola Sava Munćan Kruščica',
			'Belocrkvanska gimnazija i ekonomska škola',
			'Tehnička škola Sava Munćan',
		),
		'Beograd - Barajevo'         => array(
			'Osnovna škola Knez Sima Marković',
			'Osnovna škola Pavle Popović',
		),
		'Beograd - Voždovac'         => array(
			'Osnovna škola Bora Stanković',
			'Osnovna muzička škola Petar Konjović',
			'Osnovna škola Branislav Nušić',
			'Osnovna škola Vasa Čarapić',
			'Osnovna škola Veselin Masleša',
			'Osnovna škola Vojvoda Putnik',
			'Osnovna Škola Vojvoda Stepa',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Đura Daničić',
			'Osnovna škola Zmaj Jova Jovanović',
			'Osnovna škola Janko Veselinović',
			'Osnovna škola Karađorđe',
			'Osnovna škola Milan Đ. Milićević',
			'Osnovna škola Filip Filipović',
			'Osnovna škola Danilo Kiš',
			'Osnovna škola Jajinci',
			'Specijalna škola Miodrag Matić',
			'Geološka i hidrometeorološka škola Milutin Milanković',
			'Dvanaesta beogradska gimnazija',
			'Druga ekonomska škola',
			'Osma beogradska gimnazija',
			'Tehnička škola za dizajn kože',
			'Škola za dizajn tekstila',
			'Škola za negu lepote',
			'Škola za osnovno i srednje obrazovanje Vožd',
		),
		'Beograd - Vračar'           => array(
			'Osnovna škola Vladislav Ribnikar',
			'Osnovna škola Jovan Miodragović',
			'Osnovna škola Kralj Petar II Karađorđević',
			'Osnovna škola NH Siniša Nikolajević',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Svetozar Marković',
			'Specijalna škola Dušan Dugalić',
			'Arhitektonska tehnička škola',
			'Muzička škola Josip Slavenski',
			'Muzička škola Josif Marinković',
			'Muzička škola Stanković',
			'Privatna gimnazija Vladislav Petković Dis',
			'Tehnička škola GSP',
			'Treća beogradska gimnazija',
			'Četrnaesta beogradska gimnazija',
		),
		'Beograd - Grocka'           => array(
			'Osnovna muzička škola Nevena Popović',
			'Osnovna škola Aleksa Šantić',
			'Osnovna škola Ilija Garašanin',
			'Osnovna škola Miloje Vasić',
			'Osnovna škola Mića Stojković',
			'Osnovna škola Nikola Tesla',
			'Osnovna škola Sveti Sava Vrčin',
			'Osnovna škola Ivo Lola Ribar',
		),
		'Beograd - Zvezdara'         => array(
			'Muzička škola Vladimir Đorđević',
			'Osnovna škola 1300 kaplara',
			'Osnovna škola Veljko Dugošević',
			'Osnovna škola Vladislav Petković Dis',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Despot Stefan Lazarević',
			'Osnovna škola Dragojlo Dudić',
			'Osnovna škola Ivan Goran Kovačić',
			'Osnovna škola Jelena Ćetković',
			'Osnovna škola Marija Bursać',
			'Osnovna škola Pavle Savić',
			'Osnovna škola Stevan Sinđelić',
			'Osnovna škola Ćirilo i Metodije',
			'Specijalna škola Boško Buha',
			'Geodetska tehnička škola',
			'Gimnazija Singidunum',
			'Građevinska škola',
			'Građevinsko tehnička škola Branko Žeželj',
			'Zubotehnička škola',
			'Medicinska škola',
			'Sedma beogradska gimnazija',
			'Tehnoart Beograd - škola za mašinstvo i umetničke zanate',
			'Farmaceutsko - fizioterapeutska škola',
			'Šesta beogradska gimnazija',
		),
		'Beograd - Zemun'            => array(
			'Osnovna škola Branko Radičević',
			'Osnovna škola Gavrilo Princip',
			'Osnovna škola Gornja Varoš',
			'Osnovna škola Ilija Birčanin',
			'Osnovna škola Majka Jugovića',
			'Osnovna škola Mihajlo Pupin',
			'Osnovna škola Petar Kočić',
			'Osnovna škola Rade Končar',
			'Osnovna škola Sava Jovanović Sirogojno',
			'Osnovna škola Sava Šumanović',
			'Osnovna škola Svetislav Golubović Mitraljeta',
			'Osnovna škola Svetozar Miletić',
			'Osnovna škola Sonja Marinković',
			'Osnovna škola Stanko Marić',
			'Osnovna škola Sutjeska',
			'Osnovna škola Boško Palkovljević-Pinki',
			'Osnovna škola Lazar Savatić',
			'Specijalna škola Radivoj Popović',
			'Škola Branko Pešić',
			'Ekonomska škola Nada Dimić',
			'Elektrotehnička škola Zemun',
			'Zemunska gimnazija',
			'Medicinska škola Nadežda Petrović',
			'Muzička škola Kosta Manojlović',
			'Politehnika - škola za nove tehnologije',
			'Pravno-birotehnička škola Dimitrije Davidović',
			'Savremena gimnazija',
			'Saobraćajno-tehnička škola',
			'Srednja pravno ekonomska škola',
			'Srednja škola za informacione tehnologije',
			'Škola za učenike oštećenog vida Veljko Ramadanović',
		),
		'Beograd - Mladenovac'       => array(
			'Osnovna muzička škola Stevan Hristić',
			'Osnovna škola Bisa Simić',
			'Osnovna škola Bora Lazić',
			'Osnovna škola Živomir Savković',
			'Osnovna škola Milica Milošević',
			'Osnovna škola Momčilo Živojinović',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Kosta Đukić',
		),
		'Beograd - Novi Beograd'     => array(
			'Osnovna škola 20.oktobar',
			'Osnovna škola Borislav Pekić',
			'Osnovna škola Vlada Obradović Kameni',
			'Osnovna škola Dragan Lukić',
			'Osnovna škola Duško Radović',
			'Osnovna škola Đuro Strugar',
			'Osnovna škola Ivan Gundulić',
			'Osnovna škola Jovan Sterija Popović',
			'Osnovna škola Kneginja Milica',
			'Osnovna škola Kralj Aleksandar I',
			'Osnovna škola Laza Kostić',
			'Osnovna škola Marko Orešković',
			'Osnovna škola Milan Rakić',
			'Osnovna škola Mladost',
			'Osnovna škola Nadežda Petrović',
			'Osnovna škola Novi Beograd',
			'Osnovna škola Ratko Mitrović',
			'Osnovna škola Jovan Dučić',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Radoje Domanović',
			'Grafičko-medijska škola',
			'Deveta gimnazija Mihailo Petrović Alas',
			'Deseta gimnazija Mihajlo Pupin',
			'Srednja turistička škola',
			'Srednja škola Kosta Cukić',
			'Srednjoškolski obrazovni centar Smartanac',
			'Tehnička škola Zmaj',
			'Tehnička škola Novi Beograd',
		),
		'Beograd - Obrenovac'        => array(
			'Osnovna škola 14.oktobar',
			'Osnovna škola Grabovac',
			'Osnovna škola Draževac',
			'Osnovna škola Živojin Perić',
			'Osnovna škola Jefimija',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Ljubomir Aćimović',
			'Osnovna škola Nikola Tesla',
			'Osnovna škola Posavski partizani',
			'Osnovna škola Prva obrenovačka osnovna škola',
			'Gimnazija',
			'Poljoprivredno-hemijska škola',
			'Tehnička škola',
			'Biblioteka Vlada Aksentijević',
		),
		'Beograd - Palilula'         => array(
			'Osnovna škola Vasa Pelagić',
			'Osnovna škola Dr Arčibald Rajs',
			'Osnovna škola Zaga Malivuk',
			'Osnovna škola Ivan Milutinović',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Jovan Ristić',
			'Osnovna škola Jovan Cvijić',
			'Osnovna škola Kraljica Marija',
			'Osnovna škola Milena Pavlović Barili',
			'Osnovna škola Olga Petrov',
			'Osnovna škola Oslobodioci Beograda',
			'Osnovna škola Rade Drainac',
			'Osnovna škola Starina Novak',
			'Osnovna škola Stevan Dukić',
			'Osnovna škola Stevan Sremac',
			'Osnovna škola Filip Višnjić',
			'Osnovna škola Vlada Aksentijević',
			'Elektrotehnička škola Rade Končar',
			'Železnička tehnička škola',
			'Peta beogradska gimnazija',
			'Poljoprivredna škola PK Beograd',
			'Prva privatna ugostiteljsko-turistička škola',
			'Srednja tehnička PTT škola',
		),
		'Beograd - Rakovica'         => array(
			'Osnovna škola 14. oktobar',
			'Osnovna škola Branko Ćopić',
			'Osnovna škola Vladimir Rolović',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Ivo Andrić',
			'Osnovna škola Kosta Abrašević',
			'Osnovna škola Nikola Tesla',
			'Osnovna škola France Prešern',
			'Gimnazija Patrijarh Pavle',
			'Evropska poslovna škola',
			'Mašinska škola Radoje Dakić',
			'Muzička škola Davorin Jenko',
			'Peta ekonomska škola',
			'Srednja zanatska škola',
		),
		'Beograd - Savski Venac'     => array(
			'Muzička škola Stanislav Binički',
			'Osnovna škola Vojvoda Mišić',
			'Osnovna škola Vojvoda Radomir Putnik',
			'Osnovna škola Isidora Sekulić',
			'Osnovna škola Petar Petrović Njegoš',
			'Osnovna škola Radojka Lakić',
			'Osnovna škola Stefan Nemanja',
			'Specijalna škola Anton Skala',
			'Specijalna škola Dr Dragan Hercog',
			'Gimnazija Kreativno pero',
			'Gimnazija Sveti Sava',
			'Gimnazija Stefan Nemanja',
			'Medicinska škola Beograd',
			'Srednja medicinska škola Milutin Milanković',
			'Srednja stručna škola Zaharija Stefanović Orfelin',
			'Srednja škola Artimedia',
			'Ugostiteljsko-turistička škola',
			'Filološka gimnazija',
			'Četvrta beogradska gimnazija',
			'Škola za brodarstvo, brodogradnju i hidrogradnju',
			'Škola za dizajn',
			'Škola za oštećene sluhom-nagluve Stefan Dečanski',
		),
		'Beograd - Sopot'            => array(
			'Osnovna škola Janko Katić',
			'Osnovna škola Jelica Milovanović',
			'Osnovna škola Milorad Mića Marković',
			'Osnovna škola Cana Marjanović',
		),
		'Beograd - Stari Grad'       => array(
			'Baletska škola Lujo Davičo',
			'Osnovna škola Braća Baruh',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Kralj Petar Prvi',
			'Osnovna škola Mihailo Petrović Alas',
			'Osnovna škola Skadarlija',
			'Osnovna škola Drinka Pavlović',
			'Specijalna škola Dragan Kovačević',
			'Baletska škola Lujo Davičo',
			'Vazduhoplovna akademija',
			'Elektrotehnička škola Nikola Tesla',
			'Elektrotehnička škola Stari grad',
			'Matematička gimnazija',
			'Tehnička škola Drvo-Art',
			'Muzička škola Mokranjac',
			'Pravno-poslovna škola',
			'Prva beogradska gimnazija',
			'Prva ekonomska škola',
			'Privatna gimnazija Milena Pavlović-Barili',
			'Računarska gimnazija',
			'Sportska gimnazija',
			'Srednja medicinska škola Sveti Vasilije Ostroški',
			'Srednja škola Dositej',
			'Srednja škola za ekonomiju, pravo i administraciju',
			'Srednja škola Sveti Sava',
			'Tehnička škola DRVO ART',
			'Trgovačka škola',
		),
		'Beograd - Surčin'           => array(
			'Osnovna škola 22. oktobar',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vožd Karađorđe',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dušan Vukasović - Diogen',
			'Osnovna škola Stevan Sremac',
		),
		'Beograd - Čukarica'         => array(
			'Osnovna škola Aca Milosavljević',
			'Osnovna škola Braća Jerković',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Duško Radović',
			'Osnovna škola Đorđe Krstić',
			'Osnovna škola Karađorđe',
			'Osnovna škola Ljuba Nenadović',
			'Osnovna škola Miloš Crnjanski',
			'Osnovna škola Miroslav Antić',
			'Osnovna škola Ruđer Bošković',
			'Osnovna škola Stefan Dečanski',
			'Osnovna škola Ujedinjene nacije',
			'Osnovna škola Filip Kljajić Fića',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Banović Strahinja',
			'Osnovna škola Josif Pančić',
			'Privatna osnovna škola Plavi krug',
			'Specijalna škola Miloje Pavlović',
			'Škola za osnovno i srednje obrazovanje Sveti Sava',
			'Gimnazija Ruđer Bošković',
			'Gimnazija Crnjanski',
			'Muzička škola Vatroslav Lisinski',
			'Osnovna i srednja muzička škola Amadeus',
			'Prva sportska košarkaška gimnazija',
			'Tehnička škola',
			'Trinaesta beogradska gimnazija',
			'Hemijsko-prehrambena tehnološka škola',
		),
		'Beočin'                     => array(
			'Osnovna škola Jovan Popović Susek',
			'Osnovna škola Jovan Grčić Milenko',
		),
		'Bečej'                      => array(
			'Osnovna škola Zdravko Gložanski',
			'Osnovna škola Petefi Šandor',
			'Osnovna škola Svetozar Marković Bačko Gradište',
			'Osnovna škola Sever Đurkić',
			'Osnovna škola Šamu Mihalj',
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
			'Tehnička škola',
			'Škola za osnovno i srednje obrazovanje Bratstvo',
			'Škola za osnovno muzičko vaspitanje i obrazovanje Petar Konjović',
		),
		'Blace'                      => array(
			'Osnovna škola Stojan Novaković',
			'Srednja škola',
		),
		'Bogatić'                    => array(
			'Osnovna škola Vuk Karadžić Badovinci',
			'Osnovna škola Janko Veselinović Crna Bara',
			'Osnovna škola Laza K. Lazarević Klenje',
			'Osnovna škola Mika Mitrović',
			'Osnovna škola Nikola Tesla Dublje',
			'Osnovna škola Cvetin Brkić Glušci',
			'Mačvanska srednja škola',
		),
		'Bojnik'                     => array(
			'Osnovna škola Stanimir Veljković Zele',
			'Osnovna škola Stojan Ljubić Kosančić',
			'Tehnička škola Boško Krstić',
		),
		'Boljevac'                   => array(
			'Osnovna škola 9. srpska brigada',
			'Osnovna škola Đorđe Simeonović Podgorac',
			'Osnovna škola Đura Jakšić Sumrakovac',
			'Srednja škola Nikola Tesla',
		),
		'Bor'                        => array(
			'Osnovna muzička škola Miodrag Vasiljević',
			'Osnovna škola 3.oktobar',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Dušan Radović',
			'Osnovna škola Đura jakšić Krivelj',
			'Osnovna škola Petar Radovanović Zlot',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Stanoje Miljković Brestovac',
			'Osnovna škola Vuk Karadžić',
			'Gimnazija Bora Stanković',
			'Ekonomsko-trgovinska škola',
			'Mašinsko-elektrotehnička škola',
			'Tehnička škola',
			'Škola za osnovno i srednje obrazovanje Vidovdan',
		),
		'Bosilegrad'                 => array(
			'Osnovna škola Georgi Dimitrov',
			'Gimnazija',
		),
		'Brus'                       => array(
			'Osnovna škola 1. maj Vlajkovci',
			'Osnovna škola Branko Radičević Razbojna',
			'Osnovna škola Vuk Karadžić Blaževo',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Srednja škola',
		),
		'Bujanovac'                  => array(
			'Osnovna škola Ali Bektaši Nesalce',
			'Osnovna škola Desanka Maksimović Biljača',
			'Osnovna škola Dragomir Trajković Žbevac',
			'Osnovna škola Miđeni Muhovac',
			'Osnovna škola Muarem Kadriju Veliki Trnovac',
			'Osnovna škola Sami Frašeri Lučane',
			'Osnovna škola Bora Stanković Klenike',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Naim Frašeri',
			'Osnovna škola Vuk Stefanović Karadžić Levosoje',
			'Srednja škola Sezai Suroi',
			'Stručna škola Sveti Sava',
			'Škola za osnovno muzičko obrazovanje',
		),
		'Valjevo'                    => array(
			'Osnovna škola Andra Savčić',
			'Osnovna škola Vladika Nikolaj Velimirović',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Dragoljub Ilić Dračić',
			'Osnovna škola Zdravko Jovanović Tubravić',
			'Osnovna škola Ilija Birčanin Bobova',
			'Osnovna škola Milovan Glišić',
			'Osnovna škola Milovan Glišić Kamenica',
			'Osnovna škola Miloš Marković Donje Leskovice',
			'Osnovna škola Nada Purić',
			'Osnovna škola Prva osnovna škola',
			'Osnovna škola Prota Mateja Nenadović Brankovina',
			'Osnovna škola Sveti Sava Popučke',
			'Osnovna škola Stevan Filipović Divci',
			'Osnovna škola Sestre Ilić',
			'Valjevska gimnazija',
			'Ekonomska škola',
			'Medicinska škola Dr Miša Pantić',
			'Muzička škola Živorad Grbić',
			'Poljoprivredna škola',
			'Tehnička škola',
		),
		'Varvarin'                   => array(
			'Osnovna škola Dragi Makić Bošnjane',
			'Osnovna škola Jovan Kursula',
			'Osnovna škola Mirko Tomić Obrež',
			'Osnovna škola Sveti Sava Bačina',
			'Osnovna škola Heroj Mirko Tomić Donji Krčin',
			'Srednja škola',
		),
		'Velika Plana'               => array(
			'Osnovna škola Akademik Radomir Lukić Miloševac',
			'Osnovna škola Vuk Karadžić Krnjevo',
			'Osnovna škola Drugi šumadijski odred Markovac',
			'Osnovna škola Karađorđe',
			'Osnovna škola Nadežda Petrović',
			'Osnovna škola Radica Ranković Lozovik',
			'Osnovna škola Sveti Sava',
			'Gimnazija Velika Plana',
			'Ekonomsko-ugostiteljska škola Vuk Karadžić',
			'Tehnička škola Nikola Tesla',
		),
		'Veliko Gradište'            => array(
			'Osnovna škola Vuk Karadžić Majilovac',
			'Osnovna škola Ivo Lola Ribar',
			'Osnovna škola Miša Živanović Srednjevo',
			'Srednja škola Miloje Vasić',
		),
		'Veliko Ropotovo'            => array(
			'Medicinska škola',
		),
		'Visibaba'                   => array(
			'Poljoprivredna škola',
		),
		'Vladimirci'                 => array(
			'Osnovna škola Žika Popović',
			'Osnovna škola Jovan Cvijić Debrc',
			'Posavotamnavska srednja škola',
		),
		'Vladičin Han'               => array(
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vojvoda Radomir Putnik Džep',
			'Osnovna škola Vuk Karadžić Stubal',
			'Osnovna škola Sveti Sava',
			'Gimnazija Jovan Skerlić',
			'Tehnička škola',
		),
		'Vlasotince'                 => array(
			'Osnovna škola 25. Maj Dolja Lopušnja',
			'Osnovna škola 8. oktobar',
			'Osnovna škola Božidar Miljković Gornji Prisjan',
			'Osnovna škola Braća Milenković Šišave',
			'Osnovna škola Vuk Karadžić Tegošnica',
			'Osnovna škola Dositej Obradović Svođe',
			'Osnovna škola Karađorđe Petrović Kruševica',
			'Osnovna škola Sveti Sava Gložane',
			'Osnovna škola Siniša Janić',
			'Gimnazija Stevan Jakovljević',
			'Tehnička škola',
		),
		'Vranje'                     => array(
			'Osnovna škola 1. maj Vrtogoš',
			'Osnovna škola 20 oktobar Vlase',
			'Osnovna škola Bora Stanković Tibužde',
			'Osnovna škola Branislav Nušić Rataje',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Radoje Domanović',
			'Osnovna škola Svetozar Marković',
			'Gimnazija Bora Stanković',
			'Ekonomsko-trgovinska škola',
			'Medicinska škola Dr Izabel Emsli Haton',
			'Muzička škola Stevan Mokranjac',
			'Srednja poljoprivredno-veterinarska škola Stevan Sinđelić',
			'Srednja poslovna škola Trajković',
			'Tehnička škola',
			'Hemijsko-tehnološka škola',
			'Škola za osnovno i srednje obrazovanje Vule Antić',
		),
		'Vranjska Banja'             => array(
			'Osnovna škola Kralj Petar I Oslobodilac Korbevac',
			'Osnovna škola Predrag Devedžić',
		),
		'Vrbas'                      => array(
			'Osnovna muzička škola',
			'Osnovna škola 20. oktobar',
			'Osnovna škola Branko Radičević Ravno Selo',
			'Osnovna škola Branko Radičević Savino Selo',
			'Osnovna škola Bratstvo jedinstvo Kucura',
			'Osnovna škola Vuk Karadžić Bačko Dobro Polje',
			'Osnovna škola Jovan Jovanović Zmaj Zmajevo',
			'Osnovna škola Petar Petrović Njegoš',
			'Osnovna škola Svetozar Miletić',
			'Osnovna škola Bratstvo jedinstvo',
			'Gimnazija Žarko Zrenjanin',
			'Srednja medicinska škola Kozma i Damjan',
			'Srednja stručna škola 4. juli',
		),
		'Vrbovac'                    => array(
			'Tehnička škola',
		),
		'Vrnjačka Banja'             => array(
			'Osnovna škola Bane Milenković Novo Selo',
			'Osnovna škola Branko Radičević Vraneši',
			'Osnovna škola Mladost Vrnjci',
			'Osnovna škola Popinski borci',
			'Gimnazija',
			'Ugostiteljsko-turistička škola',
		),
		'Vršac'                      => array(
			'Osnovna škola Branko Radičević Veliko Središte',
			'Osnovna škola Branko Radičević Uljma',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Đura Jakšić Pavliš',
			'Osnovna škola Žarko Zrenjanin Izbište',
			'Osnovna škola Jovan Sterija Popović',
			'Osnovna škola Koriolan Doban Kuštilj',
			'Osnovna škola Mladost',
			'Osnovna škola Moša Pijade Gudurica',
			'Osnovna škola Olga Petrov Radišić',
			'Osnovna škola Paja Jovanović',
			'Gimnazija Borislav Petrov Braca',
			'Muzička škola Josif Marinković',
			'Poljoprivredna škola',
			'Hemijsko-medicinska škola',
			'Škola za osnovno i srednje obrazovanje Jelena Varjaški',
			'Školski centar Nikola Tesla',
		),
		'Vučitrn'                    => array(
			'Gimnazija',
			'Tehnička škola',
		),
		'Vučje'                      => array(
			'Srednja škola Svetozar Krstić Toza',
		),
		'Gadžin Han'                 => array(
			'Osnovna škola Vitko i Sveta',
		),
		'Golubac'                    => array(
			'Osnovna škola Veljko Dugošević Braničevo',
			'Osnovna škola Branko Radičević',
		),
		'Goraždevac'                 => array(
			'Gimnazija',
			'Ekonomska škola',
			'Mašinsko-elektrotehnička škola',
		),
		'Gornje Kusce'               => array(
			'Tehnička škola Dragi Popović',
		),
		'Gornji Milanovac'           => array(
			'Osnovna škola Arsenije Loma Rudnik',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Ivo Andrić Pranjani',
			'Osnovna škola Kralj Aleksandar I',
			'Osnovna škola Momčilo Nastasijević',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Takovski ustanak Takovo',
			'Gimnazija Takovski ustanak',
			'Ekonomsko-trgovačka škola Knjaz Miloš',
			'Tehnička škola Jovan Žujović',
		),
		'Gračanica'                  => array(
			'Građevinsko-saobraćajna škola',
			'Medicinska škola',
			'Muzička škola Stevan Mokranjac',
		),
		'Grdelica'                   => array(
			'Srednja škola',
		),
		'Grocka'                     => array(
			'Srednja škola',
		),
		'Guča'                       => array(
			'Srednja škola Dragačevo',
		),
		'Despotovac'                 => array(
			'Osnovna škola Vuk Karadžić Resavica',
			'Osnovna škola Despot Stefan Visoki',
			'Osnovna škola Đura Jakšić Plažane',
			'Osnovna škola Stevan Sinđelić Veliki Popović',
			'Osnovna škola Stevan Nemanja Stenjevac',
			'Tehnička škola',
		),
		'Dimitrovgrad'               => array(
			'Osnovna škola Hristo Botev',
			'Gimnazija Sveti Kirilo i Metodije',
		),
		'Doljevac'                   => array(
			'Osnovna škola Vuk Karadžić',
		),
		'Donja Gušterica'            => array(
			'Poljoprivredna škola',
		),
		'Dragaš'                     => array(
			'Ekonomsko-trgovinska škola',
		),
		'Žabalj'                     => array(
			'Osnovna škola Đura Jakšić Čurug',
			'Osnovna škola Žarko Zrenjanin Gospođinci',
			'Osnovna škola Jovan Jovanović Zmaj Đurđevo',
			'Osnovna škola Miloš Crnjanski',
			'Srednja škola 22. oktobar',
		),
		'Žabari'                     => array(
			'Osnovna škola Dude Jović',
			'Osnovna škola Heroj Rosa Trifunović Aleksandrovac',
		),
		'Žagubica'                   => array(
			'Osnovna škola Jovan Šerbanović Krepoljin',
			'Osnovna škola Moša Pijade',
			'Osnovna škola Jovan Šerbanović Laznica',
			'Tehnička škola',
		),
		'Žitište'                    => array(
			'Osnovna škola Miloš Crnjanski Srpski Itebej',
			'Osnovna škola Nikola Tesla Banatsko Karađorđevo',
			'Osnovna škola Sveti Sava',
		),
		'Žitorađa'                   => array(
			'Osnovna škola Toplički heroji',
			'Srednja škola',
		),
		'Zaječar'                    => array(
			'Osnovna muzička škola Stevan Mokranjac',
			'Osnovna škola 15. maj Mali Jasenovac',
			'Osnovna škola Vladislav Petković Dis Grljan',
			'Osnovna škola Vuk Karadžić Veliki Izvor',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Dositej Obradović Vražogrnac',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Jeremija Ilić-Jegor Rgotina',
			'Osnovna škola Jovan Jovanović Zmaj Salaš',
			'Osnovna škola Ljuba Nešić',
			'Osnovna škola Hajduk Veljko',
			'Osnovna škola Ljubica Radosavljević Nada',
			'Škola za osnovno i srednje obrazovanje Jelena Majstorović',
			'Gimnazija',
			'Ekonomsko-trgovačka škola',
			'Medicinska škola',
			'Tehnička škola',
		),
		'Zvečan'                     => array(
			'Srednja škola',
		),
		'Zrenjanin'                  => array(
			'Osnovna i srednja škola 9. maj',
			'Osnovna škola 2. oktobar',
			'Osnovna Škola Branko Radičević Čenta',
			'Osnovna škola Branko Ćopić Lukićevo',
			'Osnovna škola Bratstvo jedinstvo Belo Blato',
			'Osnovna škola Bratstvo Aradac',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Dositej Obradović Farkaždin',
			'Osnovna škola Dr Aleksandar Sabovljev Ečka',
			'Osnovna škola Dr Boško Vrebalov Melenci',
			'Osnovna škola Dr Jovan Cvijić',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Đura Jakšić Perlez',
			'Osnovna škola Žarko Zrenjanin',
			'Osnovna škola Jovan Dučić Klek',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Mladost Tomaševac',
			'Osnovna škola Petar Kočić Banatski Despotovac',
			'Osnovna škola Petar Petrović Njegoš',
			'Osnovna škola Sveti Sava Stajićevo',
			'Osnovna škola Svetozar Marković Toza Elemir',
			'Osnovna škola Servo Mihalj',
			'Osnovna škola Slavko Rodić Lazarevo',
			'Osnovna škola Sonja Marinković',
			'Osnovna škola Stevan Knićanin Knićanin',
			'Osnovna škola Uroš Predić Orlovat',
			'Osnovna škola 1. oktobar Botoš',
			'Ekonomsko-trgovinska škola Jovan Trajković',
			'Elektrotehnička i građevinska škola Nikola Tesla',
			'Zrenjaninska gimnazija',
			'Medicinska škola',
			'Muzička škola Josif Marinković',
			'Osnovna i srednja škola 9. Maj',
			'Poljoprivredna škola',
			'Tehnička škola',
			'Hemijsko-prehrambena i tekstilna škola Uroš Predić',
		),
		'Zubin Potok'                => array(
			'Srednja škola Grigorije Božović',
		),
		'Ivanjica'                   => array(
			'Osnovna škola Vučić Veličković Međurečje',
			'Osnovna škola Kirilo Savić Sveštica',
			'Osnovna škola Major Ilić Kušići',
			'Osnovna škola Milan Vučićević Zverac Bratljevo',
			'Osnovna škola Milinko Kušić',
			'Osnovna škola Mićo Matović Katići',
			'Osnovna škola Prof. dr. Nedeljko Košanin Devići',
			'Osnovna škola Svetozar Marković Kovilje',
			'Osnovna škola Sreten Lazarević Prilike',
			'Gimnazija',
			'Tehnička škola',
		),
		'Inđija'                     => array(
			'Osnovna škola 22. jul Krčedin',
			'Osnovna škola Branko Radičević Maradik',
			'Osnovna škola Braća Grulović Beška',
			'Osnovna škola Dr Đorđe Natošević Novi Slankamen',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Petar Kočić',
			'Osnovna škola Ruža Đurđević Crna Čortanovci',
			'Osnovna škola Dušan Jerković',
			'Osnovna škola Slobodan Bajić Paja Novi Karlovci',
			'Gimnazija',
			'Srednja škola Dr Đorđe Natošević',
			'Tehnička škola Mihajlo Pupin',
		),
		'Irig'                       => array(
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Milica Stojadinović Srpkinja Vrdnik',
			'Srednja stručna škola Borislav Mihajlović Mihiz',
		),
		'Jagodina'                   => array(
			'Muzička škola Vladimir Đorđević',
			'Osnovna škola 17. oktobar',
			'Osnovna škola Boško Đuričić',
			'Osnovna škola Branko Radičević Bunar',
			'Osnovna škola Vuk Karadžić Glogovac',
			'Osnovna škola Goran Ostojić',
			'Osnovna škola Joca Milosavljević Bagrdan',
			'Osnovna škola Ljubiša Urošević Ribare',
			'Osnovna škola Milan Mijalković',
			'Osnovna škola Rada Miljković',
			'Osnovna škola Radislav Nikčević Majur',
			'Privatna osnovna škola Crnjanski',
			'Gimnazija Svetozar Marković',
			'Ekonomsko-trgovinska škola Slavka Đurđević',
			'Elektrotehnička i građevinska škola Nikola Tesla',
			'Prva tehnička škola',
			'Srednja medicinska škola',
			'Škola za učenike oštećenog sluha i govora 11. maj',
		),
		'Kanjiža'                    => array(
			'Osnovna muzička škola',
			'Osnovna škola Aranj Janoš Trešnjevac',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Karolina Karas Horgoš',
			'Poljoprivredno-tehnički srednjoškolski centar Besedeš Jožef',
		),
		'Kikinda'                    => array(
			'Osnovna muzička škola Slobodan Malbaški',
			'Osnovna škola 1. oktobar Bašaid',
			'Osnovna škola 6. oktobar',
			'Osnovna škola Bratstvo - jedinstvo Banatska Topola',
			'Osnovna škola Vasa Stajić Mokrin',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Gligorije Popov Rusko Selo',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Žarko Zrenjanin',
			'Osnovna škola Ivo Lola Ribar Novi Kozarci',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Milivoj Omorac Iđoš',
			'Osnovna škola Mora Karolj Sajan',
			'Osnovna škola Petar Kočić Nakovo',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Slavko Rodić Banatsko Veliko Selo',
			'Osnovna škola Feješ Klara',
			'Gimnazija Dušan Vasiljev',
			'Ekonomsko-trgovinska škola',
			'Srednja stručna škola Miloš Crnjanski',
			'Tehnička škola Mihajlo Pupin',
		),
		'Kladovo'                    => array(
			'Osnovna muzička škola Konstantin Babić',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Ljubica Jovanović Radosavljević Podvrška',
			'Osnovna škola Svetozar Radić Tekija',
			'Osnovna škola Stefanija Mihajlović Brza Palanka',
			'Osnovna škola Hajduk Veljko Korbovo',
			'Srednja škola',
		),
		'Knić'                       => array(
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Rada Šubakić Gruža',
			'Osnovna škola Sveti Sava Toponica',
			'Srednja škola',
		),
		'Knjaževac'                  => array(
			'Osnovna muzička škola Predrag Milošević',
			'Osnovna škola Dimitrije Todorović Kaplar',
			'Osnovna škola Dubrava',
			'Osnovna škola Mladost',
			'Osnovna škola Vuk Karadžić',
			'Knjaževačka gimnazija',
			'Tehnička škola',
		),
		'Kovačica'                   => array(
			'Osnovna škola Lukrecija Ankucić Samoš',
			'Osnovna škola Maršal Tito Padina',
			'Osnovna škola Mihajlo Pupin Idvor',
			'Osnovna škola Mlada pokolenja',
			'Osnovna škola Moša Pijade Debeljača',
			'Osnovna škola Sava Žebeljan Crepaja',
			'Osnovna škola Sveti Georgije Uzdin',
			'Gimnazija Mihajlo Pupin',
		),
		'Kovin'                      => array(
			'Osnovna škola Bora Radić Bavanište',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Đura Filipović Pločica',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Miša Stojković Gaj',
			'Osnovna škola Paja Marganović Deliblato',
			'Osnovna škola Predrag Kožić Dubovac',
			'Osnovna škola Sava Maksimović Mramorak',
			'Osnovna škola Žarko Zrenjanin Skorenovac',
			'Gimnazija i ekonomska škola Branko Radičević',
			'Srednja stručna škola Vasa Pelagić',
		),
		'Kosjerić'                   => array(
			'Tehnička škola',
			'Osnovna škola Jordan Đukanović Varda',
			'Osnovna škola Mito Igumanović',
		),
		'Kosovska Kamenica'          => array(
			'Gimnazija',
			'Tehnička škola',
		),
		'Kosovska Mitrovica'         => array(
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
			'Medicinska škola',
			'Muzička škola Miodrag Vasiljević',
			'Tehnička škola Mihailo Petrović Alas',
			'Škola za osnovno i srednje obrazovanje Kosovski božur',
		),
		'Kostolac'                   => array(
			'Osnovna škola Jovan Cvijić',
			'Tehnička škola Nikola Tesla',
		),
		'Koceljeva'                  => array(
			'Osnovna škola Mića Stanojlović',
			'Srednja škola',
		),
		'Kragujevac'                 => array(
			'Osnovna škola 19. oktobar Maršić',
			'Osnovna škola 21. oktobar',
			'Osnovna škola Vuk Stefanović Karadžić',
			'Osnovna škola Dositej Obradović Erdeč',
			'Osnovna škola Dragiša Luković-Španac',
			'Osnovna škola Dragiša Mihajlović',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Živadinka Divac',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Julijana Ćatić Stragari',
			'Osnovna škola Miloje Simović Dragobraća',
			'Osnovna škola Milutin i Draginja Todorović',
			'Osnovna škola Mirko Jovanović',
			'Osnovna škola Moma Stanojlović',
			'Osnovna škola Natalija Nana Nedeljković Grošnica',
			'Osnovna škola Prota Stevan Popović Čumić',
			'Osnovna škola Radoje Domanović',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Svetozar Marković',
			'Osnovna škola Sreten Mladenović Desimirovac',
			'Osnovna škola Stanislav Sremčević',
			'Osnovna škola Treći kragujevački bataljon',
			'Škola za osnovno obrazovanje Vukašin Marković',
			'Škola za učenike oštećenog sluha',
			'Druga kragujevačka gimnazija Liceja',
			'Ekonomska škola',
			'Medicinska škola Sestre Ninković',
			'Muzička škola Dr Miloje Milojević',
			'Prva kragujevačka gimnazija',
			'Prva tehnička škola',
			'Srednja stručna škola',
			'Srednja škola Dositej Obradović',
			'Srednja škola Sveti Arhangel',
			'Trgovinsko-ugostiteljska škola Toza Dragović',
		),
		'Kraljevo'                   => array(
			'Osnovna škola IV kraljevački bataljon',
			'Osnovna škola Braća Vilotijević',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dositej Obradović Vrba',
			'Osnovna škola Dragan Đoković Uča Lađevci',
			'Osnovna škola Dragan Marinković Adrani',
			'Osnovna škola Živan Maričić Žiča',
			'Osnovna škola Jovan Dučić Roćevići',
			'Osnovna škola Jovan Cvijić Sirča',
			'Osnovna škola Jovo Kursula',
			'Osnovna škola Milunka Savić Vitanovac',
			'Osnovna škola Olga Milutinović Godačica',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Stefan Nemanja Brezova',
			'Osnovna škola Čibukovački partizani',
			'Osnovna škola Đura Jakšić Konarevo',
			'Osnovna škola Dimitrije Tucović',
			'Osnovna škola Milun Ivanović Ušće',
			'Osnovna škola Svetozar Marković',
			'Osnovna škola Branko Radičević Vitkovac',
			'Osnovna škola Petar Nikolić Samaila',
			'Škola za osnovno i srednje obrazovanje Ivo Lola Ribar',
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
			'Elektro-saobraćajna tehnička škola Nikola Tesla',
			'Mašinska tehnička škola 14. oktobar',
			'Medicinska škola',
			'Muzička škola Stevan Mokranjac',
			'Poljoprivredno-hemijska škola Dr Đorđe Radić',
			'Umetnička škola',
			'Šumarska škola',
		),
		'Krupanj'                    => array(
			'Osnovna škola Borivoje Ž. Milojević',
			'Osnovna škola Žikica Jovanović Španac Bela Crkva',
			'Srednja škola',
		),
		'Kruševac'                   => array(
			'Osnovna škola Brana Pavlović Konjuh',
			'Osnovna škola Branko Radičević Bivolje',
			'Osnovna škola Vasa Pelagić Padež',
			'Osnovna škola Velizar Stanković-Korčagin Veliki Šiljegovac',
			'Osnovna škola Vladislav Savić Jan Parunovac',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Despot Stefan Gornji Stepoš',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Dragomir Marković',
			'Osnovna škola Žabare',
			'Osnovna škola Jovan Jovanović Zmaj Mudrakovac',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Knez Lazar Veliki Kupci',
			'Osnovna škola Nada Popović',
			'Osnovna škola Sveti Sava Čitluk',
			'Osnovna škola Stanislav Binički Jasika',
			'Osnovna škola Strahinja Popović Dvorane',
			'Škola za osnovno i srednje obrazovanje Veselin Nikolić',
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
			'Medicinska škola',
			'Muzička škola Stevan Hristić',
			'Politehnička škola Milutin Milanković',
			'Prva tehnička škola',
			'Srednja poslovno menadžerska škola',
			'Hemijsko-tehnološka škola',
		),
		'Kula'                       => array(
			'Osnovna škola Petefi brigada',
			'Osnovna i srednja škola Pjetro Kuzmjak Ruski Krstur',
			'Osnovna škola 20. oktobar Sivac',
			'Osnovna škola Veljko Vlahović Kruščić',
			'Osnovna škola Vuk Karadžić Crvenka',
			'Osnovna škola Isa Bajić',
			'Osnovna škola Nikola Tesla Lipar',
			'Ekonomsko-trgovinska škola',
			'Srednja tehnička škola Mihajlo Pupin',
			'Srednja škola Peti april',
			'Škola za osnovno muzičko obrazovanje',
		),
		'Kuršumlija'                 => array(
			'Osnovna škola Drinka Pavlović',
			'Osnovna škola Miloje Zakić',
			'Gimnazija',
			'Ekonomsko-tehnička škola',
		),
		'Kučevo'                     => array(
			'Osnovna škola Veljko Dugošević Turija',
			'Osnovna škola Milutin Milanković Rabrovo',
			'Osnovna škola Slobodan Jović Voluja',
			'Osnovna škola Ugrin Branković',
			'Ekonomsko-trgovinska i mašinska škola',
		),
		'Lazarevac'                  => array(
			'Gimnazija',
			'Poslovno menadžerska škola',
			'Tehnička škola Kolubara',
			'Muzička škola Marko Tajčević',
			'Osnovna škola Vojislav Voka Savić',
			'Osnovna škola Dule Karaklajić',
			'Osnovna škola Knez Lazar',
			'Osnovna škola Milorad Labudović Labud',
			'Osnovna škola Rudovci',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Slobodan Penezić Krcun',
			'Osnovna škola Vuk Karadžić Stepojevac',
			'Osnovna škola Diša Đurđević',
			'Osnovna škola Mihailo Mladenović Selja',
		),
		'Lajkovac'                   => array(
			'Srednja škola 17. septembar',
			'Osnovna škola Dimitrije Tucović Jabučje',
			'Osnovna škola Mile Dubljević',
		),
		'Laplje Selo'                => array(
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
		),
		'Lapovo'                     => array(
			'Srednja škola',
			'Osnovna škola Svetozar Marković',
		),
		'Lebane'                     => array(
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Radovan Kovačević Maksim',
			'Osnovna škola Radoje Domanović Bošnjace',
			'Gimnazija',
			'Srednja tehnička škola Vožd Karađorđe',
		),
		'Leposavić'                  => array(
			'Srednja škola Nikola Tesla',
		),
		'Leskovac'                   => array(
			'Osnovna škola Vuk Karadžić Pečenjevce',
			'Osnovna škola Bora Stanković Bogojevce',
			'Osnovna škola Bora Stanković Vučje',
			'Osnovna škola Bora Stanković Guberevac',
			'Osnovna škola Branko Radičević Brestovac',
			'Osnovna škola Vasa Pelagić',
			'Osnovna škola Vožd Karađorđe',
			'Osnovna škola Vuk Karadžić Velika Grabovnica',
			'Osnovna škola Đura Jakšić Turekovac',
			'Osnovna škola Josif Pančić Orašac',
			'Osnovna škola Kosta Stamenković',
			'Osnovna škola Milutin Smiljković Vinarce',
			'Osnovna škola Nikola Skobaljić Veliko Trnjane',
			'Osnovna škola Petar Tasić',
			'Osnovna škola Svetozar Marković',
			'Osnovna škola Slavko Zlatanović Miroševce',
			'Osnovna škola Aca Sinadinović Predejane',
			'Osnovna škola Desanka Maksimović Grdelica',
			'Osnovna škola Radoje Domanović Manojlovce',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Josif Kostić',
			'Osnovna škola Trajko Stamenković',
			'Škola za osnovno i srednje obrazovanje 11. oktobar',
			'Gimnazija',
			'Ekonomska škola Đuka Dinić',
			'Medicinska škola Bore Dimitrijevića',
			'Muzička škola Stanislav Binički',
			'Poljoprivredna škola',
			'Tehnička škola Rade Metalac',
			'Trgovinsko-ugostiteljska škola',
			'Hemijsko-tehnološka škola Božidar Đorđević Kukar',
			'Škola za osnovno i srednje obrazovanje 11.oktobar',
			'Škola za tekstil i dizajn',
		),
		'Lešak'                      => array(
			'Poljoprivredna škola',
		),
		'Loznica'                    => array(
			'Osnovna muzička škola Vuk Karadžić',
			'Osnovna škola 14.oktobar Draginac',
			'Osnovna škola Anta Bogićević',
			'Osnovna škola Vera Blagojević Banja Koviljača',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Vuk Karadžić Lipnica',
			'Osnovna škola Vukova spomen škola Tršić',
			'Osnovna škola Dositej Obradović Klupci',
			'Osnovna škola Jovan Cvijić',
			'Osnovna škola Kadinjača',
			'Osnovna škola Kralj Aleksandar I Karađorđević Jadranska Lešnica',
			'Osnovna škola Mika Mitrović Brezjak',
			'Osnovna škola Petar Tasić Lešnica',
			'Osnovna škola Sveti Sava Lipnički Šor',
			'Osnovna škola Stepa Stepanović Tekeriš',
			'Gimnazija Vuk Karadžić',
			'Srednja ekonomska škola',
			'Srednja škola Sveti Sava',
			'Tehnička škola',
		),
		'Lučani'                     => array(
			'Osnovna škola Akademik Milenko Šušić Guča',
			'Osnovna škola Vuk Karadžić Kaona',
			'Osnovna škola Goračići Goračići',
			'Osnovna škola Kotraža Kotraža',
			'Osnovna škola Marko Pajić Viča',
			'Osnovna škola Milan Blagojević',
		),
		'Ljig'                       => array(
			'Osnovna škola Sava Kerković',
			'Osnovna škola Sestre Pavlović Belanovica',
			'Srednja škola 1300 kaplara',
		),
		'Ljubovija'                  => array(
			'Osnovna škola Petar Vragolić',
			'Srednja škola Vuk Karadžić Drinska bb',
		),
		'Majdanpek'                  => array(
			'Osnovna muzička škola Ranko Krivić',
			'Osnovna škola 12. septembar',
			'Osnovna škola Branko Perić Rudna Glava',
			'Osnovna škola Velimir Markićević',
			'Osnovna škola Vuk Karadžić Donji Milanovac',
			'Osnovna škola Miladin Bučanović Vlaole',
			'Gimnazija Mile Arsenijević Bandera',
			'Tehnička škola',
		),
		'Mali Zvornik'               => array(
			'Osnovna škola Nikola Tesla Velika Reka',
			'Osnovna škola Stevan Filipović Radalj',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Braća Ribar Donja Borina',
			'Osnovna škola Miloš Gajić Amajić',
			'Srednja škola',
		),
		'Mali Iđoš'                  => array(
			'Osnovna škola Adi Endre',
			'Osnovna škola Vuk Karadžić Lovćenac',
			'Osnovna škola Nikola Đurković Feketić',
		),
		'Malo Crniće'                => array(
			'Osnovna škola Draža Marković Rođa Smoljinac',
			'Osnovna škola Đura Jakšić Toponica',
			'Osnovna škola Milisav Nikolić Boževac',
			'Osnovna škola Moša Pijade',
		),
		'Medveđa'                    => array(
			'Osnovna škola Vladimir Bukilić Tulare',
			'Osnovna škola Gornja Jablanica',
			'Osnovna škola Zenelj Hajdini Tupale',
			'Osnovna škola Partizanski dom Donji Bučumet',
			'Osnovna škola Radovan Kovačević Lece',
			'Osnovna škola Sijarinska Banja Sijarinska Banja',
			'Tehnička škola Nikola Tesla',
		),
		'Merošina'                   => array(
			'Osnovna škola Jastrebački partizani',
		),
		'Mionica'                    => array(
			'Srednja škola',
			'Osnovna škola Vojvoda Živojin Mišić Rajković',
			'Osnovna škola Milan Rakić',
		),
		'Mladenovac'                 => array(
			'Gimnazija',
			'Tehnička škola',
		),
		'Negotin'                    => array(
			'Osnovna škola Branislav Nušić Urovica',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vera Radosavljević',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Jovan Jovanović Zmaj Jabukovac',
			'Osnovna škola Momčilo Ranković Rajac',
			'Osnovna škola Pavle Ilić Veljko Dušanovac',
			'Osnovna škola Pavle Ilić Veljko Prahovo',
			'Osnovna škola Stevan Mokranjac Kobišnica',
			'Osnovna škola Hajduk Veljko Štubik',
			'Osnovna škola za lako mentalno ometenu decu 12. decembar',
			'Muzička škola Stevan Mokranjac',
			'Negotinska gimnazija',
			'Poljoprivredna škola Rajko Bosnić',
			'Tehnička škola Miomira Radosavljevića',
		),
		'Niš - Medijana'             => array(
			'Osnovna škola Ćele Kula',
			'Osnovna škola Vožd Karađorđe',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Dr Zoran Đinđić Brzi brod',
			'Osnovna škola Dušan Radović',
			'Osnovna škola Radoje Domanović',
			'Osnovna škola Ratko Vukićević',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Učitelj Tasa',
			'Osnovna škola Car Konstantin',
			'Gimnazija Bora Stanković',
			'Gimnazija Deveti maj',
			'Ekonomska škola',
			'Elektrotehnička škola Mija Stanimirović',
			'Medicinska škola Dr Milenko Hadžić',
			'Muzička škola',
			'Pravno-poslovna škola',
			'Prva niška gimnazija Stevan Sremac',
			'Prehrambeno-hemijska škola Generala Milojka',
			'Srednja škola Prokopović',
			'Trgovinska škola',
			'Ugostiteljsko-turistička škola',
			'Umetnička škola',
			'Škola mode i lepote Generala Milojka',
		),
		'Niš - Palilula'             => array(
			'Osnovna škola Branko Miljković',
			'Osnovna škola Branko Radičević Gabrovac',
			'Osnovna škola Bubanjski heroji',
			'Osnovna škola Desanka Maksimović Čokot',
			'Osnovna škola Kole Rašić',
			'Osnovna škola Kralj Petar I',
			'Osnovna škola Sreten Mladenović Mika',
			'Osnovna škola 14. oktobar',
			'Specijalna škola Bubanj',
			'Škola za osnovno i srednje obrazovanje Carica Jelena',
			'Gimnazija Svetozar Marković',
			'Mašinska škola',
		),
		'Niš - Pantelej'             => array(
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Karađorđe',
			'Osnovna škola Miroslav Antić',
			'Osnovna škola Njegoš',
			'Osnovna škola Stevan Sinđelić',
			'Osnovna škola Stefan Nemanja',
			'Osnovna škola Čegar',
		),
		'Niš - Crveni Krst'          => array(
			'Osnovna škola Branislav Nušić Donja Trnava',
			'Osnovna škola Vojislav Ilić-Mlađi Hum',
			'Osnovna škola Ivo Andrić',
			'Osnovna škola Lela Popović Miljkovac',
			'Osnovna škola Milan Rakić Medoševac',
			'Osnovna škola Prvi maj Trupale',
			'Osnovna škola Vuk Karadžić',
			'Građevinska tehnička škola Neimar',
			'Elektrotehnička škola Nikola Tesla',
			'Srednja stručna škola',
		),
		'Niška Banja'                => array(
			'Osnovna škola Đura Jakšić Jelašnica',
			'Osnovna škola Ivan Goran Kovačić',
			'Osnovna škola Nadežda Petrović Sićevo',
		),
		'Nova Varoš'                 => array(
			'Osnovna škola Vuk Karadžić Jasenovo',
			'Osnovna škola Gojko Drulović Radoinja',
			'Osnovna škola Dobrisav Dobrica Rajić Bistrica',
			'Osnovna škola Živko Ljujić',
			'Osnovna škola Knezova Raškovića Božetići',
			'Osnovna škola Momir Pucarević Akmačići',
			'Srednja škola',
		),
		'Nova Crnja'                 => array(
			'Osnovna škola 4. oktobar Vojvoda Stepa',
			'Osnovna škola Branko Radičević Aleksandrovo',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Petefi Šandor',
			'Osnovna škola Stanko Krstin Radojevo',
		),
		'Novi Bečej'                 => array(
			'Osnovna škola Dositej Obradović Bočar',
			'Osnovna škola Dr Đorđe Joanović Novo Miloševo',
			'Osnovna škola Josif Marinković',
			'Osnovna škola Milan Stančić Uča Kumane',
			'Osnovna škola Miloje Čiplić',
			'Srednja škola',
		),
		'Novi Kneževac'              => array(
			'Muzička škola',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Gimnazija i stručna škola Dositej Obradović',
		),
		'Novi Pazar'                 => array(
			'Osnovna škola Avdo Međedović',
			'Osnovna škola Bratstvo',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Dositej Obradović Osaonica',
			'Osnovna škola Đura Jakšić Trnava',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Jošanica Lukare',
			'Osnovna škola Meša Selimović',
			'Osnovna škola Mur Mur',
			'Osnovna škola Rastko Nemanjić Deževa',
			'Osnovna škola Rifat Burdžović Tršo',
			'Osnovna škola Stefan Nemanja',
			'Osnovna škola Ćamil Sijarić',
			'Osnovna škola Halifa Bin Zaid al Nahjan Rajčinoviće',
			'Škola za osnovno muzičko obrazovanje i vaspitanje Stevan Mokranjac',
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
			'Medicinska škola',
			'Srednja škola Novi Pazar',
			'Srednja škola Hipokrat',
			'Tehnička škola',
			'Ugostiteljsko-turistička škola',
			'Škola za dizajn tekstila i kože',
		),
		'Novi Sad'                   => array(
			'Osnovna škola Đura Jakšić Kać',
			'Osnovna muzička škola Josip Slavenski',
			'Osnovna škola Aleksa Šantić Stepanovićevo',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vasa Stajić',
			'Osnovna škola Veljko Vlahović',
			'Osnovna škola Veljko Petrović Begeč',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Desanka Maksimović Futog',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Dušan Radović',
			'Osnovna škola Đorđe Natošević',
			'Osnovna škola Đura Daničić',
			'Osnovna škola Žarko Zrenjanin',
			'Osnovna škola Ivan Gundulić',
			'Osnovna škola Ivo Andrić Budisava',
			'Osnovna škola Ivo Lola Ribar',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Jožef Atila',
			'Osnovna škola Kosta Trifković',
			'Osnovna škola Laza Kostić Kovilj',
			'Osnovna škola Ljudovit Štur Kisač',
			'Osnovna škola Marija Trandafil Veternik',
			'Osnovna škola Miloš Crnjanski',
			'Osnovna škola Miroslav Antić Futog',
			'Osnovna škola Mihajlo Pupin Veternik',
			'Osnovna škola Nikola Tesla',
			'Osnovna škola Petefi Šandor',
			'Osnovna škola Prva vojvođanska brigada',
			'Osnovna škola Sveti Kirilo i Metodije',
			'Osnovna škola Sveti Sava Rumenka',
			'Osnovna škola Svetozar Marković Toza',
			'Osnovna škola Sonja Marinković',
			'Baletska škola',
			'Gimnazija Živorad Janković',
			'Gimnazija Isidora Sekulić',
			'Gimnazija Jovan Jovanović Zmaj',
			'Gimnazija Laza Kostić',
			'Gimnazija Svetozar Marković',
			'Elektrotehnička škola Mihajlo Pupin',
			'Elitna privatna ekonomska škola i gimnazija',
			'Medicinska škola',
			'Muzička škola Isidor Bajić',
			'Prva privatna srednja optičarska škola Pašćan',
			'Prva privatna srednja frizerska škola Vojkan',
			'Privatna gimnazija E-gimnazija',
			'Računarska gimnazija Smart',
			'Saobraćajna škola Pinki',
			'Srednja mašinska škola',
			'Srednja medicinska škola Hipokrat',
			'Srednja saobraćajna škola',
			'Srednja stručna škola Krug',
			'Srednja škola Dositej Obradović',
			'Srednja škola Sveti Nikola',
			'Srednja škola Svetozar Miletić',
			'Tehnička škola Mileva Marić Ajnštajn',
			'Tehnička škola Pavle Savić',
			'Škola za dizajn Bogdan Šuput',
			'Škola za osnovno i srednje obrazovanje Milan Petrović',
		),
		'Opovo'                      => array(
			'Osnovna škola Dositej Obradović',
		),
		'Orahovac'                   => array(
			'Gimnazija Orahovac',
		),
		'Osečina'                    => array(
			'Obrazovno-vaspitni centar',
			'Osnovna škola Vojvoda Mišić Pecka',
		),
		'Odžaci'                     => array(
			'Osnovna škola Bora Stanković Karavukovo',
			'Osnovna škola Vuk Karadžić Deronje',
			'Osnovna škola Jožef Atila Bogojevo',
			'Osnovna škola Kosta Stamenković Srpski Miletić',
			'Osnovna škola Marko Orešković Bački Gračac',
			'Osnovna škola Miroslav Antić',
			'Osnovna škola Nestor Žučni Lalić',
			'Osnovna škola Nikola Tesla Bački Brestovac',
			'Osnovna škola Ratko Pavlović Ćićko Ratkovo',
			'Osnovna škola Branko Radičević',
			'Gimnazija i ekonomska škola Jovan Jovanović Zmaj',
			'Srednja stručna škola',
			'Tehnička škola',
		),
		'Pančevo'                    => array(
			'Osnovna škola 4. oktobar Glogonj',
			'Osnovna škola Aksentije Maksimović Dolovo',
			'Osnovna škola Borisav Petrov Braca',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Bratstvo jedinistvo',
			'Osnovna škola Vasa Živković',
			'Osnovna škola Vuk Stefanović Karadžić Starčevo',
			'Osnovna škola Goce Delčev Jabuka',
			'Osnovna škola Dositej Obradović Omoljica',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Žarko Zrenjanin Kačarevo',
			'Osnovna škola Žarko Zrenjanin Banatsko Novo Selo',
			'Osnovna škola Isidora Sekulić',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Miroslav Antić Mika',
			'Osnovna škola Moša Pijade Ivanovo',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Stevica Jovanović',
			'Osnovna škola Olga Petrov Banatski Brestovac',
			'Škola za osnovno i srednje obrazovanje Mara Mandić',
			'Baletska škola Dimitrije Parlić',
			'Gimnazija Uroš Predić',
			'Ekonomsko-menadžerska škola',
			'Ekonomsko-trgovinska škola Paja Marganović',
			'Elektrotehnička škola Nikola Tesla',
			'Mašinska škola',
			'Medicinska škola Stevica Jovanović',
			'Muzička škola Jovan Bandur',
			'Poljoprivredna škola Josif Pančić',
			'Srednja stručna škola Vizija',
			'Tehnička škola 23. maj',
		),
		'Paraćin'                    => array(
			'Muzička škola Milenko Živković',
			'Osnovna škola Branko Krsmanović Donja Mutnica',
			'Osnovna škola Branko Krsmanović Sikirica',
			'Osnovna škola Vuk Karadžić Potočac',
			'Osnovna škola Momčilo Popović Ozren',
			'Osnovna škola Radoje Domanović',
			'Osnovna škola Đura Jakšić',
			'Osnovna škola Branko Radičević Popovac',
			'Osnovna škola Stevan Jakovljević',
			'Gimnazija',
			'Ekonomsko-trgovinska škola',
			'Mašinsko-elektrotehnička škola',
			'Tehnološka škola',
		),
		'Petrovaradin'               => array(
			'Osnovna škola 22. avgust Bukovac',
			'Osnovna škola Jovan Dučić',
			'Osnovna škola Jovan Jovanović Zmaj Sremska Kamenica',
			'Osnovna škola i predškolska ustanova Svitac Sremska Kamenica',
			'Privatna osnovna škola Tvrđava',
		),
		'Petrovac na Mlavi'          => array(
			'Osnovna škola Bata Bulić',
			'Osnovna škola Branko Radičević Melnica',
			'Osnovna škola Žarko Zrenjanin Veliko Laole',
			'Osnovna škola Jovan Šerbanović Ranovac',
			'Osnovna škola Miroslav Bukumirović-Bukum Šetonje',
			'Osnovna škola Profesor Brana Paunović Rašanac',
			'Osnovna škola Sveta Mihajlović Burovac',
			'Osnovna škola Đura Jakšić Oreškovica',
			'Srednja škola Mladost',
		),
		'Pećinci'                    => array(
			'Osnovna škola Dušan Vukasović Diogen',
			'Osnovna škola Dušan Jerković Uča Šimanovci',
			'Osnovna škola Slobodan Bajić Paja',
			'Tehnička škola Milenko Verkić',
		),
		'Pirot'                      => array(
			'Osnovna muzička škola Dr Dragutin Gostuški',
			'Osnovna škola 8.Septembar',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dušan Radović',
			'Osnovna škola Sveti Sava',
			'Gimnazija',
			'Ekonomska škola',
			'Mlekarska škola Dr. Obren Pejić',
			'Srednja stručna škola',
			'Tehnička škola',
			'Škola za osnovno i srednje obrazovanje Mladost',
		),
		'Plandište'                  => array(
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Jovan Jovanović Zmaj Hajdučica',
			'Osnovna škola Jovan Sterija Popović Velika Greda',
		),
		'Požarevac'                  => array(
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Kralj Aleksandar Prvi',
			'Osnovna škola Miloš Savić Lučica',
			'Osnovna škola Sveti vladika Nikolaj Bradarac',
			'Osnovna škola Sveti Sava',
			'Ekonomsko-trgovinska škola',
			'Medicinska škola',
			'Muzička škola Stevan Mokranjac',
			'Požarevačka gimnazija',
			'Politehnička škola',
			'Poljoprivredna škola Sonja Marinković',
			'Škola za osnovno i srednje muzičko obrazovanje Stevan Mokranjac',
		),
		'Požega'                     => array(
			'Osnovna škola Petar Leković',
			'Osnovna škola Emilija Ostojić',
			'Gimnazija Sveti Sava',
			'Tehnička škola',
		),
		'Preoce'                     => array(
			'Mašinska škola',
		),
		'Preševo'                    => array(
			'Osnovna škola 9. maj Reljan',
			'Osnovna škola Abdulah Krašnica Miratovac',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Diturija Crnotice',
			'Osnovna škola Zenelj HajdiniRajince',
			'Osnovna škola Ibrahim Keljmendi',
			'Osnovna škola Miđeni Cerevajka',
			'Osnovna škola Selami Haliči Oraovica',
			'Gimnazija Skenderbeu',
			'Srednja tehnička škola',
		),
		'Priboj'                     => array(
			'Osnovna škola 9.maj Kasidoli',
			'Osnovna škola Blagoje Polić Kratovo',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Desanka Maksimović',
			'Osnovna škola Nikola Tesla',
			'Gimnazija',
			'Mašinsko-elektrotehnička škola',
		),
		'Prijepolje'                 => array(
			'Osnovna muzička škola',
			'Osnovna škola Boško Buha Ivanje',
			'Osnovna škola Vladimir Perić Valer',
			'Osnovna škola Dušan Tomašević Ćirko Kovačevac',
			'Osnovna škola Milosav Stiković',
			'Osnovna škola Mihajlo Baković Seljašnica',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Svetozar Marković Brodarevo',
			'Ekonomsko-trgovinska škola',
			'Prijepoljska gimnazija',
			'Tehnička škola',
		),
		'Osnovna škola Vuk Karadžić' => array(
			'Srednja škola Prilužje',
		),
		'Prokuplje'                  => array(
			'Muzička škola Kornelije Stanković',
			'Osnovna škola 9. oktobar',
			'Osnovna škola Vuk Karadžić Žitni Potok',
			'Osnovna škola Milić Rakić Mirko',
			'Osnovna škola Nikodije Stojanović Tatko',
			'Osnovna škola Ratko Pavlović Ćićko',
			'Osnovna škola Svetislav Mirković Nenad Mala Plana',
			'Specijalna škola Sveti Sava',
			'Gimnazija',
			'Medicinska škola Dr. Aleksa Savić',
			'Poljoprivredna škola Radoš Jovanović Selja',
			'Tehnička škola 15.maj',
		),
		'Ražanj'                     => array(
			'Osnovna škola Vuk Karadžić Vitoševac',
			'Osnovna škola Ivan Vušović',
		),
		'Osnovna škola Trajko Perić' => array(
			'Srednja škola Ranilug',
		),
		'Rača'                       => array(
			'Osnovna škola Karađorđe',
			'Srednja škola Đura Jakšić',
		),
		'Raška'                      => array(
			'Osnovna škola Josif Pančić Baljevac',
			'Osnovna škola Jošanička banja Jošanička banja',
			'Osnovna škola Sutjeska Supnje',
			'Osnovna škola Raška',
			'Gimnazija',
			'Srednja škola Kraljica Jelena',
		),
		'Rekovac'                    => array(
			'Osnovna škola Dušan Popović Belušić',
			'Osnovna škola Svetozar Marković',
			'Poljoprivredno-veterinarska škola',
		),
		'Ruma'                       => array(
			'Osnovna muzička škola Teodor Toša Andrejević',
			'Osnovna škola 23. oktobar Klenak',
			'Osnovna škola Branko Radičević Nikinci',
			'Osnovna škola Veljko Dugošević',
			'Osnovna škola Dositej Obradović Putinci',
			'Osnovna škola Dušan Jerković',
			'Osnovna škola Zmaj Jova Jovanović',
			'Osnovna škola Ivo Lola Ribar',
			'Osnovna škola Milivoj Petković - Fećko Platičevo',
			'Osnovna škola Miloš Crnjanski Hrtkovci',
			'Osnovna škola Nebojša Jerković Buđanovci',
			'OŠ VI udarna vojvođanska brigada Grabovci',
			'Gimnazija Stevan Puzić',
			'Srednja poljoprivredno-prehrambena škola Stevan Petrović - Brile',
			'Srednja stručna škola Branko Radičević',
			'Srednja tehnička škola Milenko Brzak - Uča',
		),
		'Ruski Krstur'               => array(
			'Osnovna škola i gimnazija Pjetro Kuzmjak',
		),
		'Svilajnac'                  => array(
			'Osnovna škola Branko Radičević Sedlare',
			'Osnovna škola Vožd Karađorđe Kušiljevo',
			'Osnovna škola Stevan Sinđelić Vojska',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Poljoprivredno-veterinarska škola',
			'Srednja škola Svilajnac',
		),
		'Svrljig'                    => array(
			'Osnovna škola Dobrila Stambolić',
			'Stručna škola Dušan Trivunac Dragoš',
		),
		'Senta'                      => array(
			'Osnovna muzička škola Stevan Mokranjac',
			'Osnovna škola Petefi Šandor',
			'Osnovna škola Stevan Sremac',
			'Osnovna škola Temerkenj Ištvan - Tornjoš',
			'Osnovna škola Turzo Lajoš',
			'Gimnazija za talentovane učenike Boljai',
			'Ekonomsko-trgovinska škola',
			'Senćanska gimnazija',
			'Srednja medicinska škola',
		),
		'Sečanj'                     => array(
			'Osnovna škola Aleksa Šantić',
			'Osnovna škola Braća Stefanović Neuzina',
			'Osnovna škola Veljko Đuričin Jarkovac',
			'Osnovna škola Vuk Karadžić Konak',
			'Osnovna škola Žarko Zrenjanin Boka',
			'Osnovna škola Ivo Lola Ribar Sutjeska',
			'Osnovna škola Slavko Rodić Krajišnik',
			'Osnovna škola Stevan Aleksić Jaša Tomić',
			'Srednja škola Vuk Karadžić',
		),
		'Sjenica'                    => array(
			'Osnovna škola 12. decembar',
			'Osnovna škola Branko Radičević Štavalj',
			'Osnovna škola Bratstvo-jedinstvo Duga Poljana',
			'Osnovna škola Vuk Karadžić Kladnica',
			'Osnovna škola Jovan Jovanović Zmaj Raždaginja',
			'Osnovna škola Rifat Burdžović Tršo Karajukića Bunari',
			'Osnovna škola Sveti Sava Bare',
			'Osnovna škola Svetozar Marković',
			'Gimnazija Jezdimir Lović',
			'Tehničko-poljoprivredna škola',
		),
		'Smederevo'                  => array(
			'Osnovna škola Branislav Nušić',
			'Osnovna škola Branko Radičević Lugavčina',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vožd Karađorđe Vodanj',
			'Osnovna škola Vuk Karadžić Lipe',
			'Osnovna škola Dimitrije Davidović',
			'Osnovna škola Dositej Obradović Vranovo',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Dr Jovan Cvijić',
			'Osnovna škola Đura Jakšić Mala Krsna',
			'Osnovna škola Ivo Andrić Radinac',
			'Osnovna škola Ivo Lola Ribar Skobalj',
			'Osnovna škola Ilija M. Kolarac Kolari',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Sava Kovačević Mihajlovac',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Svetitelj Sava Drugovac',
			'Osnovna škola Heroj Sveta Mladenović Saraorci',
			'Osnovna škola Heroj Srba Osipaonica',
			'Gimnazija',
			'Ekonomsko-trgovinska škola 16 oktobar',
			'Muzička škola Kosta Manojlović',
			'Tekstilno-tehnološka i poljoprivredna škola Despot Đurađ',
			'Tehnička škola',
		),
		'Smederevska Palanka'        => array(
			'Osnovna muzička škola Božidar Trudić',
			'Osnovna škola Brana Jevtić Kusadak',
			'Osnovna škola Đorđe Jovanović Selevac',
			'Osnovna škola Milija Rakić Cerovac',
			'Osnovna škola Radomir Lazić Azanja',
			'Osnovna škola Heroj Ivan Muker',
			'Osnovna škola Heroj Radmila Šišković',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Lazar Stanojević Ratari',
			'Osnovna škola Nikola Tesla Golobok',
			'Osnovna škola Olga Milošević',
			'Osnovna škola Stanoje Glavaš Glibovac',
			'Mašinsko-elektrotehnička škola Goša',
			'Palanačka gimnazija',
			'Srednja škola Žikica Damnjanović',
		),
		'Sokobanja'                  => array(
			'Osnovna škola Mitropolit Mihailo',
			'Srednja škola Branislav Nušić',
		),
		'Sombor'                     => array(
			'Osnovna škola 22. oktobar Bački Monoštor',
			'Osnovna škola Avram Mrazović',
			'Osnovna škola Aleksa Šantić Aleksa Šantić',
			'Osnovna škola Branko Radičević Stapar',
			'Osnovna škola Bratstvo jedinstvo Svetozar Miletić',
			'Osnovna škola Bratstvo jedinstvo',
			'Osnovna škola Bratstvo-jedinstvo Bezdan',
			'Osnovna škola Dositej Obradović',
			'Osnovna škola Ivan Goran Kovačić Stanišić',
			'Osnovna škola Ivo Lola Ribar',
			'Osnovna škola Kiš Ferenc Telečka',
			'Osnovna škola Laza Kostić Gakovo',
			'Osnovna škola Miroslav Antić Čonoplja',
			'Osnovna škola Moše Pijade Bački Breg',
			'Osnovna škola Nikola Vukićević',
			'Osnovna škola Nikola Tesla Kljajićevo',
			'Osnovna škola Ognjena Price Kolut',
			'Osnovna škola Petefi Šandor Doroslovo',
			'Osnovna škola Petar Kočić Riđica',
			'Škola za osnovno i srednje obrazovanje Vuk Karadžić',
			'Gimnazija Veljko Petrović',
			'Muzička škola Petar Konjović',
			'Srednja ekonomska škola',
			'Srednja medicinska škola Dr Ružica Rip',
			'Srednja poljoprivredno-prehrambena škola',
			'Srednja tehnička škola',
			'Srednja škola Sveti Sava',
		),
		'Sopot'                      => array(
			'Ekonomsko-trgovinska škola',
			'Mašinska škola Kosmaj',
		),
		'Srbobran'                   => array(
			'Osnovna škola Vuk Karadžić Srbobran',
			'Osnovna škola Jovan Jovanović Zmaj Srbobran',
			'Osnovna škola Petar Drapšin Turija',
			'Osnovna škola Žarko Zrenjanin Uča Nadalj',
			'Gimnazija i ekonomska škola Svetozar Miletić',
		),
		'Sremska Mitrovica'          => array(
			'Osnovna škola Boško Palkovljević Pinki',
			'Osnovna škola Branko Radičević Kuzmin',
			'Osnovna škola Dobrosav Radosavljević Narod Mačvanska Mitrovica',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Slobodan Bajić Paja',
			'Osnovna škola Triva Vitasović Lebarnik Laćarak',
			'Osnovna škola Jovan Jovanović Zmaj Martinci',
			'Škola za osnovno i srednje obrazovanje Radivoj Popović',
			'Ekonomska škola 9. Maj',
			'Medicinska škola Draginja Nikšić',
			'Mitrovačka gimnazija',
			'Muzička škola Petar Krančević',
			'Prehrambeno-šumarska i hemijska škola',
			'Srednja tehnička škola Nikola Tesla',
		),
		'Sremski Karlovci'           => array(
			'Osnovna škola 23. oktobar',
			'Karlovačka gimnazija',
			'Srednja informatička škola',
			'Srednja poslovno menadžerska škola',
		),
		'Srpska Crnja'               => array(
			'Srednja škola Đura Jakšić',
		),
		'Stanišor'                   => array(
			'Muzička škola',
		),
		'Stara Pazova'               => array(
			'Osnovna škola 23.oktobar Golubinci',
			'Osnovna škola Boško Palkovljević Pinki',
			'Osnovna škola Vera Miščević Belegiš',
			'Osnovna škola Milan Hadžić Vojka',
			'Osnovna škola Nikola Tesla Novi Banovci',
			'Osnovna škola Rastko Nemanjić - Sveti Sava Nova Pazova',
			'Osnovna škola Simeon Aranicki',
			'Osnovna škola Slobodan Savković Stari Banovci',
			'Osnovna škola Heroj Janko Čmelik',
			'Gimnazija Branko Radičević',
			'Ekonomsko-trgovinska škola Vuk Karadžić',
			'Tehnička škola',
			'Škola za osnovno i srednje obrazovanje Anton Skala',
		),
		'Subotica'                   => array(
			'Osnovna škola Sonja Marinković',
			'Osnovna i srednja škola Žarko Zrenjanin',
			'Osnovna škola 10. oktobar',
			'Osnovna škola Bosa Milićević Novi Žednik',
			'Osnovna škola Vladimir Nazor Đurđin',
			'Osnovna škola Vuk Karadžić Bajmok',
			'Osnovna škola Đuro Salaj',
			'Osnovna škola Ivan Goran Kovačić',
			'Osnovna škola Ivan Milutinović',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Jovan Mikić',
			'Osnovna škola Kizur Ištvan',
			'Osnovna škola Majšanski put',
			'Osnovna škola Matija Gubec Donji Tavankut',
			'Osnovna škola Matko Vuković',
			'Osnovna škola Miroslav Antić Palić',
			'Osnovna škola Petefi Šandor Hajdukovo',
			'Osnovna škola Pionir Stari Žednik',
			'Osnovna škola Sveti Sava',
			'Osnovna škola Sečenji Ištvan',
			'Osnovna škola Hunjadi Janoš Čantavir',
			'Gimnazija za talentovane učenike Deže Kostolanji',
			'Gimnazija Svetozar Marković',
			'Ekonomska srednja škola Bosa Milićević',
			'Ekonomska škola Global',
			'Muzička škola',
			'Politehnička škola',
			'Srednja medicinska škola',
			'Tehnička škola Ivan Sarić',
			'Hemijsko-tehnološka škola',
			'Školski centar Dositej Obradović',
		),
		'Suvo Grlo'                  => array(
			'Tehnička škola',
		),
		'Surdulica'                  => array(
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Akademik Đorđe Lazarević Vlasina Okruglica',
			'Osnovna škola Ivo Lola Ribar Klisura',
			'Osnovna škola Pera Mačkatovac',
			'Osnovna škola Sveti Sava Božica',
			'Osnovna škola Jovan Jovanović Zmaj',
			'Osnovna škola Bora Stanković Jelašica',
			'Gimnazija Svetozar Marković',
			'Poljoprivredno-šumarska škola Josif Pančić',
			'Tehnička škola Nikola Tesla',
		),
		'Sušica'                     => array(
			'Elektrotehnička škola Mihajlo Pupin',
		),
		'Temerin'                    => array(
			'Osnovna škola Danilo Zelenović Sirig',
			'Osnovna škola Kokai Imre',
			'Osnovna škola Petar Kočić',
			'Osnovna škola Slavko Rodić Bački Jarak',
			'Srednja škola Lukijan Mušicki',
		),
		'Titel'                      => array(
			'Osnovna škola Isidora Sekulić Šajkaš',
			'Osnovna škola Svetozar Miletić',
			'Srednja tehnička škola Mileva Marić',
		),
		'Topola'                     => array(
			'Srednja škola Kralj Petar Prvi',
			'Osnovna škola Živko Tomić Donja Šatornja',
			'Osnovna škola Karađorđe',
			'Osnovna škola Milan Blagojević Natalinci',
			'Osnovna škola Milutin Jelenić Gornja Trnava',
			'Osnovna škola Sestre Radović Belosavci',
		),
		'Trgovište'                  => array(
			'Osnovna škola Bora Stanković Novo Selo',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vuk Karadžić Donji Stajevac',
			'Osnovna škola Žarko Zrenjanin Uča Radovnica',
			'Srednja stručna škola Milutin Bojić',
		),
		'Trstenik'                   => array(
			'Muzička škola Kornelije Stanković',
			'Osnovna škola Dobrica Ćosić Velika Drenova',
			'Osnovna škola Živadin Apostolović',
			'Osnovna škola Jovan Jovanović Zmaj Stopanja',
			'Osnovna škola Knjeginja Milica Donji Ribnik',
			'Osnovna škola Ljubivoje Bajić Medveđa',
			'Osnovna škola Miodrag Čajetinac Čajka',
			'Osnovna škola Rade Dodić Milutovac',
			'Osnovna škola Sveti Sava',
			'Gimnazija Vuk Karadžić',
			'Tehnička škola',
		),
		'Tutin'                      => array(
			'Osnovna škola 25. maj Delimeđe',
			'Osnovna škola Aleksa Đilas Bećo Istočni Mojstir',
			'Osnovna škola Aleksa Šantić Crkvine',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dr Ibrahim Bakić Leskova',
			'Osnovna škola Meša Selimović Ribariće',
			'Osnovna škola Rifat Burdžović Tršo',
			'Gimnazija',
			'Tehnička škola',
		),
		'Ćićevac'                    => array(
			'Osnovna škola Vojvoda Prijezda Stalać',
			'Osnovna škola Dositej Obradović',
		),
		'Ćuprija'                    => array(
			'Muzička škola Dušan Skovran',
			'Osnovna škola 13. oktobar',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Đura Jakšić',
			'Gimnazija',
			'Medicinska škola',
			'Tehnička škola',
			'Škola za muzičke talente',
		),
		'Ub'                         => array(
			'Muzička škola Petar Stojanović',
			'Osnovna škola Dušan Danilović Radljevo',
			'Osnovna škola Milan Munjas',
			'Osnovna škola Rajko Mihajlović Banjani',
			'Osnovna škola Sveti Sava Pambukovica',
			'Gimnazija Branislav Petronijević',
			'Tehnička škola',
		),
		'Užice'                      => array(
			'Osnovna škola Aleksa Dejović Sevojno',
			'Osnovna škola Bogosav Janković Kremna',
			'Osnovna škola Đura Jakšić Ravni',
			'Osnovna škola Miodrag Milovanović Lune Karan',
			'Osnovna škola Nada Matić',
			'Osnovna škola Stari Grad',
			'Osnovna škola Dušan Jerković',
			'Osnovna škola Slobodan Sekulić',
			'Osnovna škola za obrazovanje učenika sa smetnjama u razvoju Miodrag V. Matić',
			'Prva Osnovna škola Kralj Petra II',
			'Ekonomska škola',
			'Medicinska škola',
			'Muzička škola Vojislav - Lale Stefanović',
			'Tehnička škola Radoje Ljubičić',
			'Tehnička škola',
			'Užička gimnazija',
			'Umetnička škola',
		),
		'Umka'                       => array(
			'Škola za osnovno i srednje obrazovanje Sveti Sava',
		),
		'Futog'                      => array(
			'Poljoprivredna škola',
		),
		'Crvenka'                    => array(
			'Srednja stručna škola',
		),
		'Crna Trava'                 => array(
			'Osnovna škola Aleksandar Stojanović',
			'Tehnička škola Milentije Popović',
		),
		'Čajetina'                   => array(
			'Osnovna škola Dimitrije Tucović',
			'Osnovna škola Milivoje Borović Mačkat',
			'Osnovna škola Savo Jovanović Sirogojno Sirogojno',
			'Ugostiteljsko-turistička škola',
		),
		'Čačak'                      => array(
			'Osnovna škola Božo Tomić Prijevor',
			'Osnovna škola Vladislav Petković Dis Zablaće',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Đeneral Marko Đ. Katanić Bresnica',
			'Osnovna škola Milica Pavlović',
			'Osnovna škola Preljina Preljina',
			'Osnovna škola Sveti Sava Atenica',
			'Osnovna škola Stepa Stepanović Gornja Gorevnica',
			'Osnovna škola Tanasko Rajić',
			'Osnovna škola Tatomir Anđelić Mrčajevci',
			'Osnovna škola Filip Filipović',
			'Osnovna škola Branislav Petrović Slatina',
			'Osnovna škola Sveti đakon Avakum Trnava',
			'Osnovna škola 22 decembar Donja Trepča',
			'Osnovna škola Dr Dragiša Mišović',
			'Osnovna škola Ratko Mitrović',
			'Škola za osnovno i srednje obrazovanje 1.Novembar',
			'Gimnazija',
			'Ekonomska škola',
			'Mašinsko-saobraćajna škola',
			'Medicinska škola',
			'Muzička škola Dr Vojislav Vučković',
			'Prehrambeno-ugostiteljska škola',
			'Tehnička škola',
			'Škola za osnovno i srednje obrazovanje 1. novembar',
		),
		'Čoka'                       => array(
			'Osnovna škola Dr Tihomir Ostojić Ostojićevo',
			'Osnovna škola Jovan Popović',
			'Osnovna škola Servo Mihalj Padej',
			'Hemijsko-prehrambena srednja škola',
		),
		'Šabac'                      => array(
			'Osnovna škola Vojvoda Stepa Lipolist',
			'Osnovna škola Vuk Karadžić',
			'Osnovna škola Dositej Obradović Volujac',
			'Osnovna škola Janko Veselinović',
			'Osnovna škola Jevrem Obrenović',
			'Osnovna škola Jovan Cvijić Zminjak',
			'Osnovna škola Kralj Aleksandar Karađorđević Prnjavor',
			'Osnovna škola Laza K. Lazarević',
			'Osnovna škola Majur Majur',
			'Osnovna škola Nata Jeličić',
			'Osnovna škola Nikolaj Velimirović',
			'Osnovna škola Stojan Novaković',
			'Specijalna škola Sveti Sava',
			'Ekonomska škola Stana Milanović',
			'Medicinska škola Dr Andra Jovanović',
			'Muzička škola Mihailo Vukdragović',
			'Srednja ekonomsko-poslovna škola',
			'Srednja poljoprivredna škola',
			'Stručna hemijska i tekstilna škola',
			'Tehnička škola',
			'Šabačka gimnazija',
			'Škola primenjenih umetnosti',
		),
		'Šid'                        => array(
			'Muzička škola Filip Višnjić',
			'Osnovna škola Branko Radičević',
			'Osnovna škola Vuk Karadžić Adaševci',
			'Osnovna škola Sava Šumanović Erdevik',
			'Osnovna škola Sremski front',
			'Osnovna škola Filip Višnjić Morović',
			'Specijalna škola Jovan Jovanović Zmaj',
			'Gimnazija Sava Šumanović',
			'Tehnička škola Nikola Tesla',
		),
		'Šilovo'                     => array(
			'Gimnazija',
		),
		'Štrpce'                     => array(
			'Ekonomsko-trgovinska škola',
		),
	),
);

